fruits=[]
f1=input("Enter the fruits name :")
f1=fruits.append(f1)
f2=input("Enter the fruits name :")
f2=fruits.append(f2)
f3=input("Enter the fruits name :")
f3=fruits.append(f3)
f4=input("Enter the fruits name :")
f4=fruits.append(f4)
f5=input("Enter the fruits name :")
f5=fruits.append(f5)
print(fruits)